import React from 'react';
import { Brain, Cpu, Database, GraduationCap, Languages, Moon, Network, Radio, ShieldCheck, Sparkles, Target, TrendingDown, Workflow } from 'lucide-react';
import { AppTheme, LiveStateResponse, SystemResourcesData } from '../types';

interface Props { liveState: LiveStateResponse | null; resources: SystemResourcesData | null; theme: AppTheme; }
type AnyRecord = Record<string, any>;
const text=(v:any)=>{if(v==null||v==='')return '—';if(typeof v==='string')return v;try{return JSON.stringify(v)}catch{return String(v)}};
const pick=(root:any,paths:string[],fallback:any='—')=>{for(const path of paths){const v=path.split('.').reduce((x,k)=>x==null?undefined:x[k],root);if(v!==undefined&&v!==null&&v!=='')return v}return fallback};
const ago=(v:any)=>{const n=Number(v||0);if(!n)return '—';const s=Math.max(0,(Date.now()-(n>1e12?n:n*1000))/1000);return s<60?`${Math.floor(s)}s ago`:s<3600?`${Math.floor(s/60)}m ago`:`${Math.floor(s/3600)}h ago`};
function Node({label,value,icon:Icon,accent='#5b8def',theme,wide=false}:{label:string;value:any;icon?:React.ElementType;accent?:string;theme:AppTheme;wide?:boolean}){const dark=theme==='dark',display=text(value);return <div className={`min-w-0 ${wide?'sm:flex-[1.7]':'flex-1'} min-h-[62px] flex items-center gap-2 px-2.5 py-2 border rounded-md ${dark?'bg-white/[.018] border-white/10':'bg-slate-50 border-slate-200'}`} title={display}>{Icon&&<span className="w-6 h-6 shrink-0 flex items-center justify-center border rounded" style={{color:accent,background:`${accent}12`,borderColor:`${accent}25`}}><Icon size={12}/></span>}<div className="min-w-0 flex-1"><div className="text-[8px] uppercase tracking-[.13em] text-slate-500 truncate">{label}</div><div className="mt-0.5 text-[10px] font-bold leading-tight break-words max-h-[36px] overflow-y-auto pr-1" style={{color:accent}}>{display}</div></div></div>}
function Rail({title,subtitle,icon:Icon,accent,theme,children}:{title:string;subtitle?:string;icon:React.ElementType;accent:string;theme:AppTheme;children:React.ReactNode}){const dark=theme==='dark';return <section className={`trace-root overflow-hidden ${dark?'trace-dark':'trace-light'}`}><div className="px-3 py-2.5 sm:px-4"><div className="flex items-center gap-2 mb-2"><span className="w-6 h-6 shrink-0 flex items-center justify-center border rounded" style={{color:accent,background:`${accent}12`,borderColor:`${accent}25`}}><Icon size={12}/></span><div className="min-w-0"><div className="text-[10px] font-bold uppercase tracking-wider truncate">{title}</div>{subtitle&&<div className="text-[8px] text-slate-500 truncate">{subtitle}</div>}</div></div><div className="flex flex-wrap gap-1.5">{children}</div></div></section>}
export function CognitiveMonitoringCards({liveState,resources,theme}:Props){
 const state:AnyRecord=liveState||{},learning:AnyRecord=state.learning||{},organs:AnyRecord=state.organs||{},extraction:AnyRecord=(state.extractions||[])[0]||{},attempts:any[]=extraction.attempts||[];
 const idle=pick(state,['idle_loop','idleLoop','monitoring.idle_loop','cognition.idle_loop'],{}),consolidation=pick(state,['memory_consolidation','memoryConsolidation','monitoring.memory_consolidation'],{}),native=pick(state,['native_response_learning','nativeResponseLearning','monitoring.native_response_learning'],{}),procedural=pick(state,['procedural_memory','proceduralMemory','monitoring.procedural_memory'],{}),typo=pick(state,['personal_typo_learning','personalTypoLearning','monitoring.personal_typo_learning'],{}),decay=pick(state,['memory_decay','memoryDecay','monitoring.memory_decay'],{}),meta=pick(state,['metacognitive_calibration','metacognitiveCalibration','monitoring.metacognitive_calibration'],{}),awareness=pick(state,['cognitive_self_awareness','cognitiveSelfAwareness','monitoring.cognitive_self_awareness'],{}),evolution=pick(state,['evolution_self_learning','evolution','monitoring.evolution'],resources?.evolution||{});
 const online=Object.values(organs).filter((o:any)=>o?.attached).length,total=Object.keys(organs).length;
 return <div className="space-y-2.5">
  <Rail title="ORGANISM HEALTH" subtitle="Heartbeat, readiness and organ attachment" icon={ShieldCheck} accent="#22c55e" theme={theme}><Node label="Heartbeat" value={state.heartbeat?.running?'ALIVE':'OFFLINE'} icon={Radio} accent={state.heartbeat?.running?'#22c55e':'#ef4444'} theme={theme}/><Node label="Beats" value={state.heartbeat?.beats??0} accent="#22c55e" theme={theme}/><Node label="Idle" value={state.heartbeat?.idle?'TRUE':'FALSE'} icon={Moon} accent="#64748b" theme={theme}/><Node label="LLM ready" value={state.llm_ready?'TRUE':'FALSE'} accent="#5b8def" theme={theme}/><Node label="Organs" value={`${online}/${total||0} ONLINE`} accent="#22c55e" theme={theme}/>{Object.entries(organs).map(([name,organ]:any)=><div key={name} className={`min-w-[132px] flex-1 min-h-[62px] flex items-center gap-2 px-2.5 border rounded-md ${organ?.attached?'bg-emerald-500/[.035] border-emerald-500/15':'bg-rose-500/[.035] border-rose-500/15'}`} title={`${name} · ${organ?.type||'unknown'}`}><span className={`w-1.5 h-1.5 rounded-full shrink-0 ${organ?.attached?'bg-emerald-400':'bg-rose-400'}`}/><div className="min-w-0"><div className="text-[9px] font-bold break-words">{name}</div><div className="text-[8px] text-slate-500 break-words">{organ?.type||'unknown'}</div><div className={`text-[8px] font-bold ${organ?.attached?'text-emerald-400':'text-rose-400'}`}>{organ?.attached?'ONLINE':'OFFLINE'}</div></div></div>)}</Rail>
  <Rail title="BACKGROUND LEARNING QUEUE" subtitle="Autonomous worker telemetry" icon={GraduationCap} accent="#8b5cf6" theme={theme}><Node label="Worker" value={learning.alive?'ALIVE':'OFFLINE'} icon={GraduationCap} accent={learning.alive?'#8b5cf6':'#ef4444'} theme={theme}/><Node label="State" value={learning.active?'ACTIVE':'IDLE'} accent="#8b5cf6" theme={theme}/><Node label="Pending" value={learning.pending??0} accent="#f59e0b" theme={theme}/><Node label="Processed" value={learning.processed??0} accent="#22c55e" theme={theme}/><Node label="Failed" value={learning.failed??0} accent="#ef4444" theme={theme}/><Node label="Dropped" value={learning.dropped??0} accent="#64748b" theme={theme}/></Rail>
  <Rail title="SYSTEM RESOURCES" subtitle="Process and model telemetry" icon={Cpu} accent="#5b8def" theme={theme}><Node label="Platform" value={pick(resources,['platform'],'Snapdragon ARM64')} icon={Cpu} theme={theme}/><Node label="Max RSS RAM" value={`${resources?.process?.max_rss_mb??'—'} MB`} accent="#06b6d4" theme={theme}/><Node label="CPU" value={`${((resources?.process?.user_cpu_seconds??0)+(resources?.process?.system_cpu_seconds??0)).toFixed(2)} s`} theme={theme}/><Node label="LLM backend" value={resources?.llm?.backend||'—'} wide theme={theme}/><Node label="Cognitive path" value={pick(resources,['cognitive_pipeline','cognitive_path'],state.fallback_active?'NATIVE FIRST · GROQ FALLBACK':'NATIVE FIRST')} accent="#22c55e" wide theme={theme}/></Rail>
  <Rail title="RECENT SCHEMA EXTRACTIONS" subtitle="Perception source and fallback chain" icon={Workflow} accent="#5b8def" theme={theme}><Node label="Schema" value={extraction.schema||'perception'} theme={theme}/><Node label="Used" value={extraction.stage_used||(state.fallback_active?'safe_fallback':'primary')} accent={state.fallback_active?'#f59e0b':'#22c55e'} theme={theme}/><Node label="Attempts" value={attempts.length?attempts.map(a=>`${a.stage}:${a.ok?'ok':'fail'}`).join(' → '):'—'} wide accent="#f59e0b" theme={theme}/><Node label="Fallback" value={state.fallback_active?'ACTIVE':'CLEAR'} accent={state.fallback_active?'#f59e0b':'#22c55e'} theme={theme}/></Rail>
  <Rail title="IDLE LOOP ACTIVITY" subtitle="Autonomous no-op cycles" icon={Moon} accent="#64748b" theme={theme}><Node label="Last cycle" value={pick(idle,['last_cycle','lastCycle','message'],'NO-OP — no pending goals')} wide theme={theme}/><Node label="Cycles" value={pick(idle,['cycles','cycle_count','count'])} theme={theme}/><Node label="Last activity" value={ago(pick(idle,['timestamp','last_cycle_at','lastCycleAt'],0))} theme={theme}/></Rail>
  <Rail title="MEMORY CONSOLIDATION" subtitle="Episodic → semantic · idle-time" icon={Database} accent="#06b6d4" theme={theme}><Node label="Run" value={pick(consolidation,['run','run_number','runNumber'])} theme={theme}/><Node label="Examined" value={pick(consolidation,['examined','examined_count'])} theme={theme}/><Node label="Candidates" value={pick(consolidation,['candidates','candidate_count'])} theme={theme}/><Node label="Promoted" value={pick(consolidation,['promoted_to_semantic','promoted'])} accent="#22c55e" theme={theme}/></Rail>
  <Rail title="NATIVE RESPONSE LEARNING" subtitle="Zero-LLM-cost templates" icon={Sparkles} accent="#8b5cf6" theme={theme}><Node label="Templates" value={pick(native,['templates_learned','templatesLearned'],0)} accent="#8b5cf6" theme={theme}/><Node label="LLM hits saved" value={pick(native,['total_hits_saved_from_LLM','hits_saved'],0)} accent="#22c55e" theme={theme}/><Node label="Last scan" value={pick(native,['last_scan','lastScan','message'],'candidates=0')} wide theme={theme}/></Rail>
  <Rail title="PROCEDURAL MEMORY" subtitle="Third memory type · learned habits" icon={Network} accent="#f59e0b" theme={theme}><Node label="Procedures" value={pick(procedural,['total_procedures','procedures'],0)} accent="#f59e0b" theme={theme}/><Node label="Hits" value={pick(procedural,['total_hits','hits'],0)} theme={theme}/><Node label="By kind" value={pick(procedural,['by_kind','byKind'],'(none learned yet)')} wide theme={theme}/></Rail>
  <Rail title="PERSONAL TYPO LEARNING" subtitle="Idiolect correction model" icon={Languages} accent="#5b8def" theme={theme}><Node label="Corrections" value={pick(typo,['learned_corrections','corrections'],0)} theme={theme}/><Node label="Pending pairs" value={pick(typo,['pending_pairs_being_tracked','pending_pairs'],0)} theme={theme}/><Node label="Threshold" value={pick(typo,['promotion_threshold','threshold'],3)} theme={theme}/></Rail>
  <Rail title="MEMORY DECAY" subtitle="Unused personal facts fade" icon={TrendingDown} accent="#64748b" theme={theme}><Node label="Last cycle" value={pick(decay,['last_cycle','message'],'No decay cycle recorded')} wide theme={theme}/><Node label="Weakened facts" value={pick(decay,['unused_facts_weakened','weakened'],0)} theme={theme}/></Rail>
  <Rail title="METACOGNITIVE CALIBRATION" subtitle="Confidence versus correctness" icon={Target} accent="#e24d6b" theme={theme}><Node label="Score" value={pick(meta,['calibration_score','score'],0)} accent="#e24d6b" theme={theme}/><Node label="Contradicted" value={pick(meta,['contradicted_facts','contradicted'],0)} theme={theme}/><Node label="Sample" value={pick(meta,['sample','evaluations'],'—')} theme={theme}/></Rail>
  <Rail title="COGNITIVE SELF-AWARENESS" subtitle="Recall, resolution and training signals" icon={Brain} accent="#14b8a6" theme={theme}><Node label="Interactions" value={pick(awareness,['total_interactions','interactions'],0)} theme={theme}/><Node label="Native rate" value={pick(awareness,['native_resolution_rate'],0)} accent="#14b8a6" theme={theme}/><Node label="LLM fallback" value={pick(awareness,['llm_fallback_rate'],0)} theme={theme}/><Node label="Direct recall" value={pick(awareness,['direct_recall'],0)} theme={theme}/><Node label="Identity" value={pick(awareness,['identity'],0)} theme={theme}/><Node label="Graph multi-hop" value={pick(awareness,['graph_multi_hop'],0)} theme={theme}/><Node label="SLM assisted" value={pick(awareness,['slm_assisted'],0)} theme={theme}/><Node label="Contradiction rate" value={pick(awareness,['contradiction_rate'],0)} theme={theme}/><Node label="Training data" value={pick(awareness,['training_data_collected','training_examples'],'—')} wide theme={theme}/></Rail>
  <Rail title="EVOLUTION & SELF-LEARNING" subtitle="Proposals generated from organism feedback" icon={Network} accent="#a855f7" theme={theme}><Node label="Total proposals" value={pick(evolution,['proposals','total'],0)} accent="#a855f7" theme={theme}/><Node label="Approved" value={pick(evolution,['approved'],0)} theme={theme}/><Node label="Applied" value={pick(evolution,['applied'],0)} theme={theme}/><Node label="Rejected" value={pick(evolution,['rejected'],0)} theme={theme}/></Rail>
 </div>;
}
