import React,{useState,useEffect}from'react';
import{Activity,Cpu,Terminal,AlertTriangle,CheckCircle2,Clock3,Sparkles,ArrowRight,RefreshCw,ExternalLink,ShieldCheck,Radio,BarChart3}from'lucide-react';
import{LiveStateResponse,SystemResourcesData,ActivityHistoryItem,AppTheme}from'../types';
import{api}from'../api/client';
import{OrganIntrospectionViewer}from'./OrganIntrospectionViewer';
import{OvernightLearningCard}from'./OvernightLearningCard';
import{SelfImprovementList}from'./SelfImprovementList';
import{MemoryDBPipeline}from'./MemoryDBPipeline';
import{TabHeader}from'./TabHeader';
import{CognitivePipelineCard}from'./CognitivePipelineCard';
import{CognitiveMonitoringCards}from'./CognitiveMonitoringCards';

interface DashboardScreenProps{onSelectTurn:(turnId:string)=>void;onNavigateToCLI:()=>void;theme:AppTheme;activeSection?:'monitor'|'memory'|'reasoning'|'organs'|'all';onSelectSection?:(section:'monitor'|'memory'|'reasoning'|'organs'|'all')=>void}

export function DashboardScreen({onSelectTurn,onNavigateToCLI,theme,activeSection='monitor'}:DashboardScreenProps){
const[liveState,setLiveState]=useState<LiveStateResponse|null>(null);const[resources,setResources]=useState<SystemResourcesData|null>(null);const[history,setHistory]=useState<ActivityHistoryItem[]>([]);const[pollIntervalMs,setPollIntervalMs]=useState(2000);const[isRefreshing,setIsRefreshing]=useState(false);const[currentSection,setCurrentSection]=useState<'monitor'|'memory'|'reasoning'|'organs'|'all'>(activeSection);useEffect(()=>{setCurrentSection(activeSection)},[activeSection]);const isDark=theme==='dark';
const fetchDashboardData=async()=>{try{setIsRefreshing(true);const[stateRes,resRes,histRes]=await Promise.all([api.getLiveState(),api.getResources(),api.getActivityHistory()]);setLiveState(stateRes);setResources(resRes);setHistory(histRes)}catch(err){console.error('Failed to load dashboard metrics:',err)}finally{setIsRefreshing(false)}};
useEffect(()=>{fetchDashboardData();const interval=pollIntervalMs>0?setInterval(fetchDashboardData,pollIntervalMs):null;return()=>{if(interval)clearInterval(interval)}},[pollIntervalMs]);
const organEntries:[string,{type:string;attached:boolean}][]=liveState?.organs?(Object.entries(liveState.organs)as[string,{type:string;attached:boolean}][]):[];const attachedCount=organEntries.filter(([_,o])=>o.attached).length;const totalOrgans=organEntries.length||10;const learning=liveState?.learning;const showMonitor=currentSection==='monitor'||currentSection==='all';const showMemory=currentSection==='memory'||currentSection==='all';const showReasoning=currentSection==='reasoning'||currentSection==='all';const showOrgans=currentSection==='organs'||currentSection==='all';
const surface=isDark?'bg-[#080b12] border-white/10 text-white':'bg-white border-slate-200 text-slate-900';const inner=isDark?'bg-white/[0.02] border-white/5':'bg-slate-50 border-slate-200';
const headerControls=<><span className="trace-tab-control">PID: {liveState?.pid||'—'}</span><select value={pollIntervalMs} onChange={e=>setPollIntervalMs(Number(e.target.value))} className="trace-tab-control cursor-pointer outline-none"><option value={1000}>POLL: 1s</option><option value={2000}>POLL: 2s</option><option value={5000}>POLL: 5s</option><option value={0}>POLL: PAUSED</option></select><button onClick={fetchDashboardData} disabled={isRefreshing} className="trace-action-btn flex items-center gap-1.5" title="Sync now" aria-label="Sync now"><RefreshCw className={`h-3 w-3 ${isRefreshing?'animate-spin':''}`}/>SYNC</button></>;
return <div className={`h-full overflow-y-auto p-3 sm:p-5 space-y-4 font-mono text-xs max-w-full ${isDark?'trace-dark':'trace-light'}`}>
{showMonitor&&<><TabHeader icon={Activity} category="JARVIS / OBSERVABILITY" title="COGNITIVE MONITOR" subtitle="Live organism runtime monitor" controls={headerControls}/>
<CognitivePipelineCard liveState={liveState} theme={theme}/>
<CognitiveMonitoringCards liveState={liveState} resources={resources} theme={theme}/>
<section id="card-system-resources" className={`rounded-xl border overflow-hidden ${surface}`}><div className="p-4"><div className="flex items-center justify-between mb-4"><div className="flex items-center gap-2"><Cpu className="w-4 h-4 text-[#5b8def]"/><h2 className="font-bold text-sm uppercase tracking-wider">System Resources</h2></div><span className="text-[10px] text-slate-500 uppercase">Resource Telemetry</span></div><div className="grid grid-cols-2 sm:grid-cols-4 gap-3"><div className={`p-3 rounded-lg border ${inner}`}><div className="text-[10px] text-slate-500 uppercase mb-1">Platform</div><div className="font-bold text-[#5b8def]">Snapdragon ARM64</div></div><div className={`p-3 rounded-lg border ${inner}`}><div className="text-[10px] text-slate-500 uppercase mb-1">Max RSS RAM</div><div className="font-bold">{resources?.process?.max_rss_mb??'—'} MB</div></div><div className={`p-3 rounded-lg border ${inner}`}><div className="text-[10px] text-slate-500 uppercase mb-1">LLM Backend</div><div className="font-bold text-xs break-words">{resources?.llm?.backend||'—'}</div></div><div className={`p-3 rounded-lg border ${inner}`}><div className="text-[10px] text-slate-500 uppercase mb-1">CPU</div><div className="font-bold">{((resources?.process?.user_cpu_seconds??0)+(resources?.process?.system_cpu_seconds??0)).toFixed(2)} s</div></div></div></div></section>
<section id="card-organism-health" className={`rounded-xl border overflow-hidden ${surface}`}><div className="p-4"><div className="flex items-center justify-between mb-4"><div className="flex items-center gap-2"><ShieldCheck className="w-4 h-4 text-emerald-400"/><h2 className="font-bold text-sm uppercase tracking-wider">Organism Health</h2></div><div className="flex items-center gap-2 text-[10px]"><span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse"/><span className="text-emerald-400 font-bold">{attachedCount}/{totalOrgans} ONLINE</span></div></div><div className={`p-3 rounded-lg border mb-3 ${inner}`}><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3 min-w-0"><div className="w-9 h-9 rounded-lg bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center shrink-0"><Radio className="w-4 h-4 text-emerald-400"/></div><div className="min-w-0"><div className="font-bold">Heartbeat Daemon</div><div className="text-[10px] text-slate-500">Organism liveness monitor</div></div></div><div className="text-right shrink-0"><div className="font-bold text-emerald-400">{liveState?.heartbeat?.beats??0} beats</div><div className="text-[10px] text-slate-500">{attachedCount}/{totalOrgans} Organs Online</div></div></div></div><div className="relative"><div className="text-[10px] uppercase tracking-wider text-slate-500 mb-2">Attached Organs</div><div className="overflow-x-auto overflow-y-hidden max-w-full"><div className="flex gap-2 w-max pb-1">{organEntries.length?organEntries.map(([name,organ])=><div key={name} className={`w-32 h-20 shrink-0 rounded-lg border p-2.5 flex flex-col justify-between ${organ.attached?'bg-emerald-500/[0.07] border-emerald-500/20':'bg-rose-500/[0.07] border-rose-500/20'}`}><div className="flex items-center justify-between gap-2"><div className={`w-2 h-2 rounded-full shrink-0 ${organ.attached?'bg-emerald-400':'bg-rose-400'}`}/><span className={`text-[8px] uppercase font-bold ${organ.attached?'text-emerald-400':'text-rose-400'}`}>{organ.attached?'ONLINE':'OFFLINE'}</span></div><div className="truncate font-bold text-[10px]">{name}</div><div className="truncate text-[9px] text-slate-500">{organ.type}</div></div>):<div className="text-slate-500 text-xs">No organ telemetry available.</div>}</div></div></div></div></section>
<section id="card-background-learning-thread" className={`rounded-xl border overflow-hidden ${surface}`}><div className="p-4"><div className="flex items-center justify-between mb-3 gap-3"><div className="flex items-center gap-2 min-w-0"><div className="w-8 h-8 rounded-lg bg-[#8b5cf6]/10 border border-[#8b5cf6]/20 flex items-center justify-center shrink-0"><Sparkles className="w-4 h-4 text-[#8b5cf6]"/></div><div className="min-w-0"><h2 className="font-bold text-sm uppercase tracking-wider truncate">Background Learning Activity Thread</h2><div className="text-[10px] text-slate-500">Autonomous learning worker activity</div></div></div><div className="px-2 py-1 rounded-lg border bg-emerald-500/10 border-emerald-500/20 text-emerald-400 text-[10px] font-bold shrink-0"><span className="inline-block w-1.5 h-1.5 rounded-full bg-emerald-400 mr-1.5 animate-pulse"/>WORKER ALIVE</div></div><div className="flex gap-2 overflow-x-auto pb-1">{[['Pending',learning?.pending??0,'text-amber-400',Clock3],['Processed',learning?.processed??0,'text-emerald-400',CheckCircle2],['Failed',learning?.failed??0,'text-rose-400',AlertTriangle],['Dropped',learning?.dropped??0,'text-slate-400',Activity]].map(([label,value,color,Icon])=>{const I=Icon as React.ElementType;return <div key={String(label)} className={`min-w-[145px] flex-1 p-2.5 rounded-lg border ${inner}`}><div className="flex items-center gap-2 text-slate-500 mb-1"><I className="w-3.5 h-3.5"/><span className="text-[10px] uppercase">{String(label)}</span></div><div className={`text-lg font-bold ${String(color)}`}>{String(value)}</div></div>})}</div></div></section>
<section id="card-activity-history" className={`rounded-xl border overflow-hidden ${surface}`}><div className="p-4"><div className="flex items-center justify-between mb-3"><div className="flex items-center gap-2"><BarChart3 className="w-4 h-4 text-[#5b8def]"/><h2 className="font-bold text-sm uppercase tracking-wider">Recent Activity History</h2></div><span className="text-[10px] text-slate-500 uppercase">Completed Turns</span></div><div className={`rounded-lg border overflow-hidden ${isDark?'bg-black/30 border-white/5':'bg-slate-950 border-slate-200'}`}><div className="max-h-72 overflow-y-auto p-2">{history.length===0?<div className="p-2 text-slate-500 text-xs">No activity history available.</div>:history.map(item=>{const running=item.endTime===null;return <div key={item.turnId} onClick={()=>onSelectTurn(item.turnId)} className={`group flex flex-wrap items-center gap-x-3 gap-y-1 px-2.5 py-2 rounded-lg cursor-pointer border border-transparent text-[10px] transition ${isDark?'hover:bg-white/[0.035] hover:border-white/5':'hover:bg-white/10 hover:border-white/5'}`}><span className="text-[#5b8def] font-bold shrink-0">{item.turnId}</span><span className="truncate max-w-[280px] text-slate-300">{item.query}</span><span className={running?'text-amber-400':'text-slate-400'}>{running?'RUNNING':`${item.durationSeconds.toFixed(2)}s`}</span><span className="flex items-center gap-1 text-slate-500">{item.stagePath.map((stage,index)=><React.Fragment key={`${item.turnId}-${stage}-${index}`}><span>{stage}</span>{index<item.stagePath.length-1&&<ArrowRight className="w-2.5 h-2.5"/>}</React.Fragment>)}</span><button onClick={e=>{e.stopPropagation();onSelectTurn(item.turnId)}} className="ml-auto text-[#5b8def] hover:text-[#7da5f4] opacity-70 group-hover:opacity-100 transition" title="Inspect turn"><ExternalLink className="w-3 h-3"/></button></div>})}</div></div></div></section>
<section id="card-internal-logs" className={`rounded-xl border overflow-hidden ${surface}`}><div className="p-4"><div className="flex items-center justify-between mb-3"><div className="flex items-center gap-2"><Terminal className="w-4 h-4 text-[#5b8def]"/><h2 className="font-bold text-sm uppercase tracking-wider">Internal Diagnostic Logs</h2></div><button onClick={onNavigateToCLI} className={`px-2.5 py-1.5 rounded-lg border flex items-center gap-1.5 text-[10px] font-bold ${isDark?'bg-white/5 hover:bg-white/10 border-white/10 text-[#5b8def]':'bg-slate-50 hover:bg-slate-100 border-slate-200 text-[#4f7ed8]'}`}><Terminal className="w-3 h-3"/>Open Virtual CLI</button></div><div className={`rounded-lg border overflow-hidden ${isDark?'bg-black/30 border-white/5':'bg-slate-950 border-slate-200'}`}><div className="max-h-72 overflow-y-auto p-3 space-y-1.5">{(liveState?.logs??[]).length===0?<div className="text-slate-500 text-xs">No diagnostic logs available.</div>:(liveState?.logs??[]).map((log,index)=>{const level=typeof log==='object'&&log!==null&&'level'in log?String((log as{level?:string}).level||'info').toLowerCase():'info';const message=typeof log==='string'?log:typeof log==='object'&&log!==null&&'message'in log?String((log as{message?:unknown}).message??''):String(log);const warning=level==='warning'||level==='warn';const error=level==='error';return <div key={index} className={`flex gap-2 text-[10px] leading-relaxed ${error?'text-rose-400':warning?'text-amber-300':isDark?'text-slate-400':'text-slate-300'}`}><span className="opacity-40 shrink-0">[{String(index+1).padStart(3,'0')}]</span><span className={`font-bold uppercase shrink-0 ${error?'text-rose-400':warning?'text-amber-400':'text-[#5b8def]'}`}>{level}</span><span className="break-words">{message}</span></div>})}</div></div></div></section></>}
{showMemory&&<MemoryDBPipeline liveState={liveState} resources={resources} theme={theme}/>} {showReasoning&&<><OvernightLearningCard theme={theme}/><SelfImprovementList theme={theme}/></>} {showOrgans&&<OrganIntrospectionViewer theme={theme}/>}</div>;
}
